version: '3.9'
services:

  WorldOfGames:
    image: amitmenashe/wog_main_img
    ports:
      - 80:5000
    env_file:
     - wog.env
    volumes:
      - guessgame_vol:/guessgame/
      - memorygame_vol:/memorygame/
      - crgame_vol:/crgame/
    networks:
      - wog_network
    depends_on:
      - GuessGame
      - MemoryGame
      - CRGame
      - DB
  
  GuessGame:
    image: amitmenashe/guessgame_img
    volumes:
      - guessgame_vol:/app
    networks:
      - wog_network

  MemoryGame:
    image: amitmenashe/memorygame_img
    volumes:
      - memorygame_vol:/app
    networks:
      - wog_network

  CRGame:
    image: amitmenashe/cr-game_img
    volumes:
      - crgame_vol:/app
    networks:
      - wog_network

  DB:
    image: amitmenashe/wog_mysql_img
    networks:
      - wog_network
    env_file:
     - wog.env
    
volumes:
  guessgame_vol:
  memorygame_vol:
  crgame_vol:

networks:
  wog_network: